### PR TITLE
Update suppben validations, issues, fileuploader

### PR DESCRIPTION
**Pull request by bryce-mcmath**
### Please check if the PR fulfills these requirements:

- [x] After these changes, the app was run and still works as expected
- [ ] Unit tests for these changes were added (if applicable)
- [x] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
Bug fixes, content update

### CODE REVIEW

**Review by harrymaynard-maximus — APPROVED** [review]
Looks good.

**Comment by harrymaynard-maximus** [comment]
It looks like the build is failing. Did some digging and it looks like GitHub has dropped support for anonymous "git://" dependency references. We might need to update our bcgov bootstrap library dependency because of this.

**Comment by bryce-mcmath** [comment]
Re-requesting review after changes

**Review by harrymaynard-maximus — APPROVED** [review]
Looks good.

**Pull request merged**
