### PR TITLE
Update landmarks, headers, required attrs, scroll methods

### PR DESCRIPTION
**Pull request by bryce-mcmath**
### Please check if the PR fulfills these requirements:

- [x] After these changes, the app was run and still works as expected
- [ ] Unit tests for these changes were added (if applicable)
- [ ] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
Previously done accessibility improvements. PLEASE RUN THE APP with this branch checked out to ensure no breaking changes

### CODE REVIEW

**Comment by cyrilbravo** [comment]
Hi Bryce, I'll test out the application once I get back from vacation but so far the code looks good. Just one question, were you able to check the mobile view and other browsers (in IE) with the new changes? Just to make sure that everything is working in mobile and different browsers.

**Review by cyrilbravo — APPROVED** [review]
Hi Bryce, Nice work on this PR! I tried to submit forms from start to finish in all applications and they all worked. One comment I noticed in the UI is the checkboxes seemed to be a bit bigger than usual (please see attached image below). Are the checkboxes supposed to be bigger? 

image

**Comment by bryce-mcmath** [comment]
Hey Cyril. They were already bigger, you can see in the test env

**Comment by cyrilbravo** [comment]
Got it. Yes, it's the same as TEST. Nevermind my comment :D Approved! :)

**Pull request merged**
